server:
  port: ${PORT:8080}

spring:
  application:
    name: demo

  datasource:
    url: ${DB_CONNECTION_URL:jdbc:postgresql://localhost:5432/service}
    hikari:
      connection-timeout: 20000
      idle-timeout: 30000
      max-lifetime: 1800000
      validation-timeout: 5000
      keepalive-time: 0
      initialization-fail-timeout: 30000
      minimum-idle: 0
      maximum-pool-size: 50
  cloud:
    gcp:
      sql:
        enabled: false
      secretmanager:
        enabled: false

management:
  endpoints:
    enabled-by-default: false
    web:
      base-path: /debug
      exposure:
        include: info
  endpoint:
    info:
      enabled: true
  metrics:
    export:
      defaults:
        enabled: false
